[package]
name = "ffms-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffms2 = "0.2.0"
structopt = "0.3.26"
y4m = "0.7.0"
